[package]
name = "aymer/template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
BridgeNet = "ffrostflame/bridgenet@2.0.0-rc4"
Loader = "sleitnick/loader@2.0.0"
Component = "sleitnick/component@2.4.6"
Comm = "sleitnick/comm@0.3.1"
Trove = "sleitnick/trove@0.5.0"
ProfileService = "t4rp/profileservice@^0.1"
Signal = "sleitnick/signal@1.3.0"
ZonePlus = "mattschrubb/zoneplus@3.2.0"
Shake = "sleitnick/shake@0.1.7"
Promise = "evaera/promise@>=4.0.0"